import React from 'react';
import { Edit, SimpleForm, TextInput, DateInput, SelectArrayInput} from 'react-admin';
import MultiLevelSelect from 'react-multi-level-selector';


const types = [
  {value:'I',label:'I'},
  {value:'II',label:'II'},
  {value:'III',label:'III'},
  {value:'III-bis',label:'III-bis'},
  {value:'IV',label:'IV'},
  {value:'IV-bis',label:'IV-bis'},
  {value:'V',label:'V'},
  {value:'VI',label:'VI'},
  {value:'VII',label:'VII'},
  {value:'VIII',label:'VIII'},
];

const options = [
  { value: 'OG1', label: 'OG1',
    options:types,
  },
  { value: 'OG2', label: 'OG2',
  options:types,
  },
  { value: 'OG3', label: 'OG3',
  options:types,
  },
  { value: 'OG4', label: 'OG4',
  options:types,
  },
  { value: 'OG5', label: 'OG5',
  options:types,
  },
  { value: 'OG6', label: 'OG6',
  options:types,
  },
  { value: 'OG7', label: 'OG7',
  options:types,
  },
  { value: 'OG8', label: 'OG8',
  options:types,
  },
  { value: 'OG9', label: 'OG9',
  options:types,
  },
  { value: 'OG10', label: 'OG10',
  options:types,
  },
  { value: 'OG11', label: 'OG11',
  options:types,
  },
  { value: 'OG12', label: 'OG12',
  options:types,
  },
  { value: 'OG13', label: 'OG13',
  options:types,
  },
  { value: 'OS1', label: 'OS1',
  options:types,
  },
  { value: 'OS2/A', label: 'OS2/A',
  options:types,
  },
  { value: 'OS2/B', label: 'OS2/B',
  options:types,
  },
  { value: 'OS3', label: 'OS3',
  options:types,
  },
  { value: 'OS4', label: 'OS4',
  options:types,
  },
  { value: 'OS5', label: 'OS5',
  options:types,
  },
  { value: 'OS6', label: 'OS6',
  options:types,
  },
  { value: 'OS7', label: 'OS7',
  options:types,
  },
  { value: 'OS8', label: 'OS8',
  options:types,
  },
  { value: 'OS9', label: 'OS9',
  options:types,
  },
  { value: 'OS10', label: 'OS10',
  options:types,
  },
  { value: 'OS11', label: 'OS11',
  options:types,
  },
  { value: 'OS12/A', label: 'OS12/A',
  options:types,
  },
  { value: 'OS12/B', label: 'OS12/B',
  options:types,
  },
  { value: 'OS13', label: 'OS13',
  options:types,
  },
  { value: 'OS14', label: 'OS14',
  options:types,
  },
  { value: 'OS15', label: 'OS15',
  options:types,
  },
  { value: 'OS16', label: 'OS16',
  options:types,
  },
  { value: 'OS17', label: 'OS17',
  options:types,
  },
  { value: 'OS18/A', label: 'OS18/B',
  options:types,
  },
  { value: 'OS19', label: 'OS19',
  options:types,
  },
  { value: 'OS20/A', label: 'OS20/B',
  options:types,
  },
  { value: 'OS21', label: 'OS21',
  options:types,
  },
  { value: 'OS22', label: 'OS22',
  options:types,
  },
  { value: 'OS23', label: 'OS23',
  options:types,
  },
  { value: 'OS24', label: 'OS24',
  options:types,
  },
  { value: 'OS25', label: 'OS25',
  options:types,
  },
  { value: 'OS26', label: 'OS26',
  options:types,
  },
  { value: 'OS27', label: 'OS27',
  options:types,
  },
  { value: 'OS28', label: 'OS28',
  options:types,
  },
  { value: 'OS29', label: 'OS29',
  options:types,
  },
  { value: 'OS30', label: 'OS30',
  options:types,
  },
  { value: 'OS31', label: 'OS31',
  options:types,
  },
  { value: 'OS32', label: 'OS32',
  options:types,
  },
  { value: 'OS33', label: 'OS33',
  options:types,
  },
  { value: 'OS34', label: 'OS34',
  options:types,
  },
  { value: 'OS35', label: 'OS35',
  options:types,
  },
];
 

const categories = [
  { id: 'OG1', name: 'OG1' },
  { id: 'OG2', name: 'OG2' },
  { id: 'OG3', name: 'OG3' },
  { id: 'OG4', name: 'OG4' },
  { id: 'OG5', name: 'OG5' },
  { id: 'OG6', name: 'OG6' },
  { id: 'OG7', name: 'OG7' },
  { id: 'OG8', name: 'OG8' },
  { id: 'OG9', name: 'OG9' },
  { id: 'OG10', name: 'OG10'},
  { id: 'OG11', name: 'OG11'},
  { id: 'OG12', name: 'OG12'},
  { id: 'OG13', name: 'OG13' },
  { id: 'OS1', name: 'OS1' },
  { id: 'OS2/A', name: 'OS2/A'},
  { id: 'OS2/B', name: 'OS2/B'},
  { id: 'OS3', name: 'OS3'},
  { id: 'OS4', name: 'OS4'},
  { id: 'OS5', name: 'OS5'},
  { id: 'OS6', name: 'OS6'},
  { id: 'OS7', name: 'OS7' },
  { id: 'OS8', name: 'OS8' },
  { id: 'OS9', name: 'OS9' },
  { id: 'OS10', name: 'OS10'},
  { id: 'OS11', name: 'OS11'},
  { id: 'OS12/A', name: 'OS12/A'},
  { id: 'OS12/B', name: 'OS12/B'},
  { id: 'OS13', name: 'OS13'},
  { id: 'OS14', name: 'OS14'},
  { id: 'OS15', name: 'OS15'},
  { id: 'OS16', name: 'OS16'},
  { id: 'OS17', name: 'OS17' },
  { id: 'OS18/A', name: 'OS18/A'},
  { id: 'OS18/B', name: 'OS18/B'},
  { id: 'OS19', name: 'OS19'},
  { id: 'OS20/A', name: 'OS20/A'},
  { id: 'OS20/B', name: 'OS20/B'},
  { id: 'OS21', name: 'OS21'},
  { id: 'OS22', name: 'OS22'},
  { id: 'OS23', name: 'OS23'},
  { id: 'OS24', name: 'OS24'},
  { id: 'OS25', name: 'OS25'},
  { id: 'OS26', name: 'OS26'},
  { id: 'OS27', name: 'OS27'},
  { id: 'OS28', name: 'OS28'},
  { id: 'OS29', name: 'OS29'},
  { id: 'OS30', name: 'OS30'},
  { id: 'OS31', name: 'OS31'},
  { id: 'OS32', name: 'OS32'},
  { id: 'OS33', name: 'OS33'},
  { id: 'OS34', name: 'OS34'},
  { id: 'OS35', name: 'OS35'},
];

const NotesEdit = (props) => {
  return (
    <Edit title="Modifica Impresa" {...props}>
      <SimpleForm>
        <TextInput required source="number" label="Numero"/>
        <TextInput required source="name" label="Ragione sociale"/>
        <TextInput required source="location" label="Località"/>
        <TextInput required source="address" label="Indirizzo"/>
        <TextInput required source="pec" label="PEC"/>
        <TextInput required source="taxcode" label="Cod. Fiscale"/>
        <MultiLevelSelect options={options} source="categories_soa" placeholder="Categorie SOA"/>
        <SelectArrayInput source="categories_not_soa" label="Categorie non SOA" choices={categories} />
        <DateInput  source="invitedDate" label="Data invito"/>
        <DateInput  source="winnerDate" label="Data aggiudicataria"/>
      </SimpleForm>
    </Edit>
  );
};

export default NotesEdit;
